require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/assembly_parts", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # AssemblyPart. As you add validations to AssemblyPart, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AssemblyPart.create! valid_attributes
      get assembly_parts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      assembly_part = AssemblyPart.create! valid_attributes
      get assembly_part_url(assembly_part)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_assembly_part_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      assembly_part = AssemblyPart.create! valid_attributes
      get edit_assembly_part_url(assembly_part)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AssemblyPart" do
        expect {
          post assembly_parts_url, params: { assembly_part: valid_attributes }
        }.to change(AssemblyPart, :count).by(1)
      end

      it "redirects to the created assembly_part" do
        post assembly_parts_url, params: { assembly_part: valid_attributes }
        expect(response).to redirect_to(assembly_part_url(AssemblyPart.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AssemblyPart" do
        expect {
          post assembly_parts_url, params: { assembly_part: invalid_attributes }
        }.to change(AssemblyPart, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post assembly_parts_url, params: { assembly_part: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested assembly_part" do
        assembly_part = AssemblyPart.create! valid_attributes
        patch assembly_part_url(assembly_part), params: { assembly_part: new_attributes }
        assembly_part.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the assembly_part" do
        assembly_part = AssemblyPart.create! valid_attributes
        patch assembly_part_url(assembly_part), params: { assembly_part: new_attributes }
        assembly_part.reload
        expect(response).to redirect_to(assembly_part_url(assembly_part))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        assembly_part = AssemblyPart.create! valid_attributes
        patch assembly_part_url(assembly_part), params: { assembly_part: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested assembly_part" do
      assembly_part = AssemblyPart.create! valid_attributes
      expect {
        delete assembly_part_url(assembly_part)
      }.to change(AssemblyPart, :count).by(-1)
    end

    it "redirects to the assembly_parts list" do
      assembly_part = AssemblyPart.create! valid_attributes
      delete assembly_part_url(assembly_part)
      expect(response).to redirect_to(assembly_parts_url)
    end
  end
end
