
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  username: postgres
  password: postgres
  host: localhost
  port: 54321

development:
  <<: *default
  database: editor_app_books_development

test:
  <<: *default
  database: editor_app_books_test

production:
  <<: *default
  database: editor_app_books_production
  username: editor_app_books
  password: <%= ENV["EDITOR_APP_BOOKS_DATABASE_PASSWORD"] %>
